apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: new-temp.cloud-platform.service.justice.gov.uk
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://cloud-platform-kops-state/new-temp/new-temp.cloud-platform.service.justice.gov.uk
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-eu-west-2a-1
      name: "1"
    - instanceGroup: master-eu-west-2a-2
      name: "2"
    - instanceGroup: master-eu-west-2a-3
      name: "3"
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-eu-west-2a-1
      name: "1"
    - instanceGroup: master-eu-west-2a-2
      name: "2"
    - instanceGroup: master-eu-west-2a-3
      name: "3"
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.13.12
  masterPublicName: api.new-temp.cloud-platform.service.justice.gov.uk
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-west-2a
    type: Public
    zone: eu-west-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: new-temp.cloud-platform.service.justice.gov.uk
  name: master-eu-west-2a-1
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: c4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-2a-1
  role: Master
  subnets:
  - eu-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: new-temp.cloud-platform.service.justice.gov.uk
  name: master-eu-west-2a-2
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: c4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-2a-2
  role: Master
  subnets:
  - eu-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: new-temp.cloud-platform.service.justice.gov.uk
  name: master-eu-west-2a-3
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: c4.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-west-2a-3
  role: Master
  subnets:
  - eu-west-2a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: new-temp.cloud-platform.service.justice.gov.uk
  name: nodes
spec:
  image: kope.io/k8s-1.13-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t2.medium
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - eu-west-2a

